management:
  endpoint:
    health:
      enabled: true  # 开启健康管理
      show-details: always # 总是显示详细信息
  endpoints:
    web:
      exposure:
        include: "*" # 开启所有web访问   exclude 是排除，注意下别写反了
debug: true
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  jpa:
    hibernate:
      #ddl-auto: create  # 每次加载 hibernate 时都会删除上一次的生成的表，然后根据你的 model 类再重新来生成新表
      #ddl-auto: create-drop  # 每次加载 hibernate 时根据 model 类生成表，但是 sessionFactory 一关闭,表就自动删除。
      ddl-auto: update  # 最常用的属性，第一次加载 hibernate 时根据 model 类会自动建立起表的结构（前提是先建立好数据库），以后加载 hibernate 时根据 model 类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等 应用第一次运行起来后才会。
      #ddl-auto: validate  # 每次加载 hibernate 时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # 默认使用的myISAM, 配置使用innoDB引擎
    database-platform: com.arm.demo.SQLiteDialect

    properties:
      hibernate.format_sql: true


  datasource: # 不配置使用默认的链接池：Hikari
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/zhaolangjing/资料/工作记录/国资委采集交换/相关资料/上报数据示例/113600007419766846_0031_1000_20200824091348_F1A3E4252DBC4BD6883E7689BB076429/113600007419766846_0031_1000_20200824091348_F1A3E4252DBC4BD6883E7689BB076429/113600007419766846_0031_1001_20200824091348_F1A3E4252DBC4BD6883E7689BB076429.db
    #driver-class-name: com.mysql.jdbc.Driver
    #username: root
    #password: wisesoft
    #url: jdbc:mysql://172.16.9.19:3306/zlj_tets?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    hikari:
      connection-test-query: select 1
server:
  servlet:
    context-path: /demo

